# Generated by Django 4.2.25 on 2025-11-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phish_buster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='sender',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='tactic_context',
            field=models.CharField(max_length=500),
        ),
    ]
