# Generated by Django 4.2.25 on 2025-11-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phish_buster', '0002_alter_question_sender_alter_question_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tactic_context',
            field=models.TextField(max_length=500),
        ),
    ]
