# Generated by Django 4.2.25 on 2025-11-01 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phish_buster', '0003_alter_question_tactic_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playeranswer',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='phish_buster.playersession'),
        ),
    ]
